export { vueInternationalization } from './plugin.js';
export type {
	LocaleDictionary,
	LocaleMessages,
	SfcTransformMode,
	VueInternationalizationOptions,
} from './plugin.js';
export {
	compileLocaleMessage,
	formatLocaleMessage,
	getLocaleMessageListIndexes,
	getLocaleMessageNamedKeys,
	hasLocaleMessagePlural,
	isIcuLocaleMessage,
} from './message.js';
export type {
	LocaleMessageAst,
	LocaleMessageContext,
	LocaleMessageListValues,
	LocaleMessageNamedValues,
	LocaleMessageSyntax,
	LocaleMessageToken,
	LocaleMessageValue,
	LocaleMessageValues,
} from './message.js';
export {
	Internationalization,
	createComponentLocale,
	createComponentLocalizer,
	createInternationalization,
	defineInternationalization,
	formatLocaleTemplate,
	setActiveInternationalization,
	useDateTimeFormat,
	useInternationalization,
	useLocale,
	useLocalizer,
	useNumberFormat,
} from './runtime.js';
export type {
	InternationalizationInstance,
	InternationalizationRuntimeOptions,
	InternationalizationScopeName,
	LocaleBundle,
	LocaleDateTimeFormatName,
	LocaleDateTimeFormatOptions,
	LocaleDateTimeFormatSource,
	LocaleDateTimeFormatter,
	LocaleDateTimeValue,
	LocaleLocalizerDictionary,
	LocaleLocalizerScope,
	LocaleLoader,
	LocaleMessageFunction,
	LocaleNumberFormatName,
	LocaleNumberFormatOptions,
	LocaleNumberFormatSource,
	LocaleNumberFormatter,
	LocaleNumberValue,
	RuntimeLocaleDictionary,
	LocaleTemplateFunction,
	LocaleTemplateValue,
	LocaleTemplateValues,
} from './runtime.js';
